// Code generated by MockGen. DO NOT EDIT.
// Source: mcp_service.go
//
// Generated by this command:
//
//	mockgen -source=mcp_service.go -destination=mock/mcp_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "krss/backend/internal/model"
	service "krss/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMCPService is a mock of MCPService interface.
type MockMCPService struct {
	ctrl     *gomock.Controller
	recorder *MockMCPServiceMockRecorder
	isgomock struct{}
}

// MockMCPServiceMockRecorder is the mock recorder for MockMCPService.
type MockMCPServiceMockRecorder struct {
	mock *MockMCPService
}

// NewMockMCPService creates a new mock instance.
func NewMockMCPService(ctrl *gomock.Controller) *MockMCPService {
	mock := &MockMCPService{ctrl: ctrl}
	mock.recorder = &MockMCPServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPService) EXPECT() *MockMCPServiceMockRecorder {
	return m.recorder
}

// CreateServer mocks base method.
func (m *MockMCPService) CreateServer(ctx context.Context, input service.MCPServerInput) (model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServer", ctx, input)
	ret0, _ := ret[0].(model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServer indicates an expected call of CreateServer.
func (mr *MockMCPServiceMockRecorder) CreateServer(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServer", reflect.TypeOf((*MockMCPService)(nil).CreateServer), ctx, input)
}

// DeleteServer mocks base method.
func (m *MockMCPService) DeleteServer(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServer indicates an expected call of DeleteServer.
func (mr *MockMCPServiceMockRecorder) DeleteServer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServer", reflect.TypeOf((*MockMCPService)(nil).DeleteServer), ctx, id)
}

// FetchFeedItems mocks base method.
func (m *MockMCPService) FetchFeedItems(ctx context.Context, feed model.Feed) (service.MCPFetchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFeedItems", ctx, feed)
	ret0, _ := ret[0].(service.MCPFetchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFeedItems indicates an expected call of FetchFeedItems.
func (mr *MockMCPServiceMockRecorder) FetchFeedItems(ctx, feed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFeedItems", reflect.TypeOf((*MockMCPService)(nil).FetchFeedItems), ctx, feed)
}

// GetServer mocks base method.
func (m *MockMCPService) GetServer(ctx context.Context, id int64) (model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServer", ctx, id)
	ret0, _ := ret[0].(model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServer indicates an expected call of GetServer.
func (mr *MockMCPServiceMockRecorder) GetServer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockMCPService)(nil).GetServer), ctx, id)
}

// Inspect mocks base method.
func (m *MockMCPService) Inspect(ctx context.Context, id int64, req service.MCPInspectRequest) (service.MCPInspectResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", ctx, id, req)
	ret0, _ := ret[0].(service.MCPInspectResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockMCPServiceMockRecorder) Inspect(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockMCPService)(nil).Inspect), ctx, id, req)
}

// ListServers mocks base method.
func (m *MockMCPService) ListServers(ctx context.Context) ([]model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServers", ctx)
	ret0, _ := ret[0].([]model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServers indicates an expected call of ListServers.
func (mr *MockMCPServiceMockRecorder) ListServers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServers", reflect.TypeOf((*MockMCPService)(nil).ListServers), ctx)
}

// ListTools mocks base method.
func (m *MockMCPService) ListTools(ctx context.Context, id int64) (service.MCPToolListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTools", ctx, id)
	ret0, _ := ret[0].(service.MCPToolListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTools indicates an expected call of ListTools.
func (mr *MockMCPServiceMockRecorder) ListTools(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTools", reflect.TypeOf((*MockMCPService)(nil).ListTools), ctx, id)
}

// OAuthCallback mocks base method.
func (m *MockMCPService) OAuthCallback(ctx context.Context, state, code string) (model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuthCallback", ctx, state, code)
	ret0, _ := ret[0].(model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OAuthCallback indicates an expected call of OAuthCallback.
func (mr *MockMCPServiceMockRecorder) OAuthCallback(ctx, state, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthCallback", reflect.TypeOf((*MockMCPService)(nil).OAuthCallback), ctx, state, code)
}

// OAuthDiscovery mocks base method.
func (m *MockMCPService) OAuthDiscovery(ctx context.Context, id int64) (service.OAuthDiscoveryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuthDiscovery", ctx, id)
	ret0, _ := ret[0].(service.OAuthDiscoveryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OAuthDiscovery indicates an expected call of OAuthDiscovery.
func (mr *MockMCPServiceMockRecorder) OAuthDiscovery(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthDiscovery", reflect.TypeOf((*MockMCPService)(nil).OAuthDiscovery), ctx, id)
}

// OAuthRevoke mocks base method.
func (m *MockMCPService) OAuthRevoke(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuthRevoke", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// OAuthRevoke indicates an expected call of OAuthRevoke.
func (mr *MockMCPServiceMockRecorder) OAuthRevoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthRevoke", reflect.TypeOf((*MockMCPService)(nil).OAuthRevoke), ctx, id)
}

// OAuthStart mocks base method.
func (m *MockMCPService) OAuthStart(ctx context.Context, id int64, redirectURI, scope, clientID, clientSecret string) (service.OAuthStartResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OAuthStart", ctx, id, redirectURI, scope, clientID, clientSecret)
	ret0, _ := ret[0].(service.OAuthStartResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OAuthStart indicates an expected call of OAuthStart.
func (mr *MockMCPServiceMockRecorder) OAuthStart(ctx, id, redirectURI, scope, clientID, clientSecret any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OAuthStart", reflect.TypeOf((*MockMCPService)(nil).OAuthStart), ctx, id, redirectURI, scope, clientID, clientSecret)
}

// RedetectTransport mocks base method.
func (m *MockMCPService) RedetectTransport(ctx context.Context, id int64) (service.MCPTestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedetectTransport", ctx, id)
	ret0, _ := ret[0].(service.MCPTestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RedetectTransport indicates an expected call of RedetectTransport.
func (mr *MockMCPServiceMockRecorder) RedetectTransport(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedetectTransport", reflect.TypeOf((*MockMCPService)(nil).RedetectTransport), ctx, id)
}

// SuggestMapping mocks base method.
func (m *MockMCPService) SuggestMapping(ctx context.Context, id int64, req service.MCPSuggestRequest) (service.MCPSuggestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestMapping", ctx, id, req)
	ret0, _ := ret[0].(service.MCPSuggestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestMapping indicates an expected call of SuggestMapping.
func (mr *MockMCPServiceMockRecorder) SuggestMapping(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestMapping", reflect.TypeOf((*MockMCPService)(nil).SuggestMapping), ctx, id, req)
}

// TestServer mocks base method.
func (m *MockMCPService) TestServer(ctx context.Context, id int64) (service.MCPTestResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestServer", ctx, id)
	ret0, _ := ret[0].(service.MCPTestResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestServer indicates an expected call of TestServer.
func (mr *MockMCPServiceMockRecorder) TestServer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestServer", reflect.TypeOf((*MockMCPService)(nil).TestServer), ctx, id)
}

// UpdateServer mocks base method.
func (m *MockMCPService) UpdateServer(ctx context.Context, id int64, input service.MCPServerInput) (model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServer", ctx, id, input)
	ret0, _ := ret[0].(model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServer indicates an expected call of UpdateServer.
func (mr *MockMCPServiceMockRecorder) UpdateServer(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServer", reflect.TypeOf((*MockMCPService)(nil).UpdateServer), ctx, id, input)
}
