services:
  krss:
    image: ghcr.io/hu2327401139/krss:latest
    container_name: krss
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - KRSS_LOG_LEVEL=info
      # - KRSS_SWAGGER=true  # Enable Swagger API docs at /swagger/index.html
    restart: always
