// Code generated by MockGen. DO NOT EDIT.
// Source: feed_service.go
//
// Generated by this command:
//
//	mockgen -source=feed_service.go -destination=mock/feed_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFeedService is a mock of FeedService interface.
type MockFeedService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedServiceMockRecorder
	isgomock struct{}
}

// MockFeedServiceMockRecorder is the mock recorder for MockFeedService.
type MockFeedServiceMockRecorder struct {
	mock *MockFeedService
}

// NewMockFeedService creates a new mock instance.
func NewMockFeedService(ctrl *gomock.Controller) *MockFeedService {
	mock := &MockFeedService{ctrl: ctrl}
	mock.recorder = &MockFeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedService) EXPECT() *MockFeedServiceMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockFeedService) Add(ctx context.Context, feedURL string, folderID *int64, titleOverride, feedType string) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, feedURL, folderID, titleOverride, feedType)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockFeedServiceMockRecorder) Add(ctx, feedURL, folderID, titleOverride, feedType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockFeedService)(nil).Add), ctx, feedURL, folderID, titleOverride, feedType)
}

// AddMCP mocks base method.
func (m *MockFeedService) AddMCP(ctx context.Context, input service.MCPFeedAddInput) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMCP", ctx, input)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMCP indicates an expected call of AddMCP.
func (mr *MockFeedServiceMockRecorder) AddMCP(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMCP", reflect.TypeOf((*MockFeedService)(nil).AddMCP), ctx, input)
}

// AddWithoutFetch mocks base method.
func (m *MockFeedService) AddWithoutFetch(ctx context.Context, feedURL string, folderID *int64, titleOverride, feedType string) (model.Feed, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddWithoutFetch", ctx, feedURL, folderID, titleOverride, feedType)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddWithoutFetch indicates an expected call of AddWithoutFetch.
func (mr *MockFeedServiceMockRecorder) AddWithoutFetch(ctx, feedURL, folderID, titleOverride, feedType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddWithoutFetch", reflect.TypeOf((*MockFeedService)(nil).AddWithoutFetch), ctx, feedURL, folderID, titleOverride, feedType)
}

// Delete mocks base method.
func (m *MockFeedService) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeedServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeedService)(nil).Delete), ctx, id)
}

// DeleteBatch mocks base method.
func (m *MockFeedService) DeleteBatch(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockFeedServiceMockRecorder) DeleteBatch(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockFeedService)(nil).DeleteBatch), ctx, ids)
}

// List mocks base method.
func (m *MockFeedService) List(ctx context.Context, folderID *int64) ([]model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, folderID)
	ret0, _ := ret[0].([]model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFeedServiceMockRecorder) List(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFeedService)(nil).List), ctx, folderID)
}

// MergeInto mocks base method.
func (m *MockFeedService) MergeInto(ctx context.Context, sourceID, targetID int64) (service.FeedMergeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeInto", ctx, sourceID, targetID)
	ret0, _ := ret[0].(service.FeedMergeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergeInto indicates an expected call of MergeInto.
func (mr *MockFeedServiceMockRecorder) MergeInto(ctx, sourceID, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeInto", reflect.TypeOf((*MockFeedService)(nil).MergeInto), ctx, sourceID, targetID)
}

// MergePreview mocks base method.
func (m *MockFeedService) MergePreview(ctx context.Context, sourceID int64, targetURL string) (service.FeedMergePreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePreview", ctx, sourceID, targetURL)
	ret0, _ := ret[0].(service.FeedMergePreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePreview indicates an expected call of MergePreview.
func (mr *MockFeedServiceMockRecorder) MergePreview(ctx, sourceID, targetURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePreview", reflect.TypeOf((*MockFeedService)(nil).MergePreview), ctx, sourceID, targetURL)
}

// Preview mocks base method.
func (m *MockFeedService) Preview(ctx context.Context, feedURL string) (service.FeedPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, feedURL)
	ret0, _ := ret[0].(service.FeedPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockFeedServiceMockRecorder) Preview(ctx, feedURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockFeedService)(nil).Preview), ctx, feedURL)
}

// Update mocks base method.
func (m *MockFeedService) Update(ctx context.Context, id int64, title string, folderID *int64, summaryPromptReminder *string) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, title, folderID, summaryPromptReminder)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFeedServiceMockRecorder) Update(ctx, id, title, folderID, summaryPromptReminder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeedService)(nil).Update), ctx, id, title, folderID, summaryPromptReminder)
}

// UpdateAIOverrides mocks base method.
func (m *MockFeedService) UpdateAIOverrides(ctx context.Context, id int64, autoTranslate, autoSummary, readerMode *bool) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAIOverrides", ctx, id, autoTranslate, autoSummary, readerMode)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAIOverrides indicates an expected call of UpdateAIOverrides.
func (mr *MockFeedServiceMockRecorder) UpdateAIOverrides(ctx, id, autoTranslate, autoSummary, readerMode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAIOverrides", reflect.TypeOf((*MockFeedService)(nil).UpdateAIOverrides), ctx, id, autoTranslate, autoSummary, readerMode)
}

// UpdateMCPConfig mocks base method.
func (m *MockFeedService) UpdateMCPConfig(ctx context.Context, id int64, input service.MCPFeedAddInput) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMCPConfig", ctx, id, input)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMCPConfig indicates an expected call of UpdateMCPConfig.
func (mr *MockFeedServiceMockRecorder) UpdateMCPConfig(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMCPConfig", reflect.TypeOf((*MockFeedService)(nil).UpdateMCPConfig), ctx, id, input)
}

// UpdateProxyOverride mocks base method.
func (m *MockFeedService) UpdateProxyOverride(ctx context.Context, id int64, update service.ProxyOverrideUpdate) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProxyOverride", ctx, id, update)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProxyOverride indicates an expected call of UpdateProxyOverride.
func (mr *MockFeedServiceMockRecorder) UpdateProxyOverride(ctx, id, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProxyOverride", reflect.TypeOf((*MockFeedService)(nil).UpdateProxyOverride), ctx, id, update)
}

// UpdateType mocks base method.
func (m *MockFeedService) UpdateType(ctx context.Context, id int64, feedType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateType", ctx, id, feedType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateType indicates an expected call of UpdateType.
func (mr *MockFeedServiceMockRecorder) UpdateType(ctx, id, feedType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateType", reflect.TypeOf((*MockFeedService)(nil).UpdateType), ctx, id, feedType)
}

// UpdateURL mocks base method.
func (m *MockFeedService) UpdateURL(ctx context.Context, id int64, feedURL string) (model.Feed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateURL", ctx, id, feedURL)
	ret0, _ := ret[0].(model.Feed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateURL indicates an expected call of UpdateURL.
func (mr *MockFeedServiceMockRecorder) UpdateURL(ctx, id, feedURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateURL", reflect.TypeOf((*MockFeedService)(nil).UpdateURL), ctx, id, feedURL)
}
