// Code generated by MockGen. DO NOT EDIT.
// Source: filter_service.go
//
// Generated by this command:
//
//	mockgen -source=filter_service.go -destination=mock/filter_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFilterService is a mock of FilterService interface.
type MockFilterService struct {
	ctrl     *gomock.Controller
	recorder *MockFilterServiceMockRecorder
	isgomock struct{}
}

// MockFilterServiceMockRecorder is the mock recorder for MockFilterService.
type MockFilterServiceMockRecorder struct {
	mock *MockFilterService
}

// NewMockFilterService creates a new mock instance.
func NewMockFilterService(ctrl *gomock.Controller) *MockFilterService {
	mock := &MockFilterService{ctrl: ctrl}
	mock.recorder = &MockFilterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterService) EXPECT() *MockFilterServiceMockRecorder {
	return m.recorder
}

// ApplyToEntries mocks base method.
func (m *MockFilterService) ApplyToEntries(ctx context.Context, feed model.Feed, entries []model.Entry) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyToEntries", ctx, feed, entries)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyToEntries indicates an expected call of ApplyToEntries.
func (mr *MockFilterServiceMockRecorder) ApplyToEntries(ctx, feed, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyToEntries", reflect.TypeOf((*MockFilterService)(nil).ApplyToEntries), ctx, feed, entries)
}

// Create mocks base method.
func (m *MockFilterService) Create(ctx context.Context, params service.FilterWriteParams) (model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFilterServiceMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFilterService)(nil).Create), ctx, params)
}

// Delete mocks base method.
func (m *MockFilterService) Delete(ctx context.Context, id int64, revert bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, revert)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockFilterServiceMockRecorder) Delete(ctx, id, revert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFilterService)(nil).Delete), ctx, id, revert)
}

// List mocks base method.
func (m *MockFilterService) List(ctx context.Context) ([]model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFilterServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFilterService)(nil).List), ctx)
}

// ListMatches mocks base method.
func (m *MockFilterService) ListMatches(ctx context.Context, filterID int64, limit int) ([]model.FilterMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatches", ctx, filterID, limit)
	ret0, _ := ret[0].([]model.FilterMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatches indicates an expected call of ListMatches.
func (mr *MockFilterServiceMockRecorder) ListMatches(ctx, filterID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatches", reflect.TypeOf((*MockFilterService)(nil).ListMatches), ctx, filterID, limit)
}

// Preview mocks base method.
func (m *MockFilterService) Preview(ctx context.Context, params service.FilterWriteParams, limit int) (service.FilterPreviewResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, params, limit)
	ret0, _ := ret[0].(service.FilterPreviewResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockFilterServiceMockRecorder) Preview(ctx, params, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockFilterService)(nil).Preview), ctx, params, limit)
}

// Revert mocks base method.
func (m *MockFilterService) Revert(ctx context.Context, filterID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revert", ctx, filterID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revert indicates an expected call of Revert.
func (mr *MockFilterServiceMockRecorder) Revert(ctx, filterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revert", reflect.TypeOf((*MockFilterService)(nil).Revert), ctx, filterID)
}

// Update mocks base method.
func (m *MockFilterService) Update(ctx context.Context, id int64, params service.FilterWriteParams) (model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, params)
	ret0, _ := ret[0].(model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFilterServiceMockRecorder) Update(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFilterService)(nil).Update), ctx, id, params)
}
