// Code generated by MockGen. DO NOT EDIT.
// Source: filter_service.go
//
// Generated by this command:
//
//	mockgen -source=filter_service.go -destination=mock/filter_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "krss/backend/internal/model"
	repository "krss/backend/internal/repository"
	service "krss/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFilterService is a mock of FilterService interface.
type MockFilterService struct {
	ctrl     *gomock.Controller
	recorder *MockFilterServiceMockRecorder
	isgomock struct{}
}

// MockFilterServiceMockRecorder is the mock recorder for MockFilterService.
type MockFilterServiceMockRecorder struct {
	mock *MockFilterService
}

// NewMockFilterService creates a new mock instance.
func NewMockFilterService(ctrl *gomock.Controller) *MockFilterService {
	mock := &MockFilterService{ctrl: ctrl}
	mock.recorder = &MockFilterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterService) EXPECT() *MockFilterServiceMockRecorder {
	return m.recorder
}

// ApplyToEntries mocks base method.
func (m *MockFilterService) ApplyToEntries(ctx context.Context, feed model.Feed, entries []model.Entry) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyToEntries", ctx, feed, entries)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyToEntries indicates an expected call of ApplyToEntries.
func (mr *MockFilterServiceMockRecorder) ApplyToEntries(ctx, feed, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyToEntries", reflect.TypeOf((*MockFilterService)(nil).ApplyToEntries), ctx, feed, entries)
}

// ApplyToHistory mocks base method.
func (m *MockFilterService) ApplyToHistory(ctx context.Context, filterID int64, limit int) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyToHistory", ctx, filterID, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ApplyToHistory indicates an expected call of ApplyToHistory.
func (mr *MockFilterServiceMockRecorder) ApplyToHistory(ctx, filterID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyToHistory", reflect.TypeOf((*MockFilterService)(nil).ApplyToHistory), ctx, filterID, limit)
}

// CountViewMatches mocks base method.
func (m *MockFilterService) CountViewMatches(ctx context.Context, contentType *string) (map[int64]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountViewMatches", ctx, contentType)
	ret0, _ := ret[0].(map[int64]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountViewMatches indicates an expected call of CountViewMatches.
func (mr *MockFilterServiceMockRecorder) CountViewMatches(ctx, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountViewMatches", reflect.TypeOf((*MockFilterService)(nil).CountViewMatches), ctx, contentType)
}

// Create mocks base method.
func (m *MockFilterService) Create(ctx context.Context, params service.FilterWriteParams) (model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, params)
	ret0, _ := ret[0].(model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFilterServiceMockRecorder) Create(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFilterService)(nil).Create), ctx, params)
}

// CreateException mocks base method.
func (m *MockFilterService) CreateException(ctx context.Context, entryID int64) (model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateException", ctx, entryID)
	ret0, _ := ret[0].(model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateException indicates an expected call of CreateException.
func (mr *MockFilterServiceMockRecorder) CreateException(ctx, entryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateException", reflect.TypeOf((*MockFilterService)(nil).CreateException), ctx, entryID)
}

// Delete mocks base method.
func (m *MockFilterService) Delete(ctx context.Context, id int64, revert bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, revert)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockFilterServiceMockRecorder) Delete(ctx, id, revert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFilterService)(nil).Delete), ctx, id, revert)
}

// List mocks base method.
func (m *MockFilterService) List(ctx context.Context) ([]model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFilterServiceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFilterService)(nil).List), ctx)
}

// ListMatches mocks base method.
func (m *MockFilterService) ListMatches(ctx context.Context, filterID int64, limit int) ([]model.FilterMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatches", ctx, filterID, limit)
	ret0, _ := ret[0].([]model.FilterMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatches indicates an expected call of ListMatches.
func (mr *MockFilterServiceMockRecorder) ListMatches(ctx, filterID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatches", reflect.TypeOf((*MockFilterService)(nil).ListMatches), ctx, filterID, limit)
}

// ParseNaturalLanguage mocks base method.
func (m *MockFilterService) ParseNaturalLanguage(ctx context.Context, text string) (service.FilterDraft, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseNaturalLanguage", ctx, text)
	ret0, _ := ret[0].(service.FilterDraft)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseNaturalLanguage indicates an expected call of ParseNaturalLanguage.
func (mr *MockFilterServiceMockRecorder) ParseNaturalLanguage(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseNaturalLanguage", reflect.TypeOf((*MockFilterService)(nil).ParseNaturalLanguage), ctx, text)
}

// Preview mocks base method.
func (m *MockFilterService) Preview(ctx context.Context, params service.FilterWriteParams, limit int) (service.FilterPreviewResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preview", ctx, params, limit)
	ret0, _ := ret[0].(service.FilterPreviewResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preview indicates an expected call of Preview.
func (mr *MockFilterServiceMockRecorder) Preview(ctx, params, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preview", reflect.TypeOf((*MockFilterService)(nil).Preview), ctx, params, limit)
}

// Revert mocks base method.
func (m *MockFilterService) Revert(ctx context.Context, filterID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revert", ctx, filterID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revert indicates an expected call of Revert.
func (mr *MockFilterServiceMockRecorder) Revert(ctx, filterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revert", reflect.TypeOf((*MockFilterService)(nil).Revert), ctx, filterID)
}

// RevertImpact mocks base method.
func (m *MockFilterService) RevertImpact(ctx context.Context, filterID int64, limit int) ([]repository.RevertImpactEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevertImpact", ctx, filterID, limit)
	ret0, _ := ret[0].([]repository.RevertImpactEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevertImpact indicates an expected call of RevertImpact.
func (mr *MockFilterServiceMockRecorder) RevertImpact(ctx, filterID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertImpact", reflect.TypeOf((*MockFilterService)(nil).RevertImpact), ctx, filterID, limit)
}

// RevertSelected mocks base method.
func (m *MockFilterService) RevertSelected(ctx context.Context, filterID int64, entryIDs []int64, includeStarred bool) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevertSelected", ctx, filterID, entryIDs, includeStarred)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevertSelected indicates an expected call of RevertSelected.
func (mr *MockFilterServiceMockRecorder) RevertSelected(ctx, filterID, entryIDs, includeStarred any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevertSelected", reflect.TypeOf((*MockFilterService)(nil).RevertSelected), ctx, filterID, entryIDs, includeStarred)
}

// TestNotify mocks base method.
func (m *MockFilterService) TestNotify(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TestNotify", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TestNotify indicates an expected call of TestNotify.
func (mr *MockFilterServiceMockRecorder) TestNotify(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TestNotify", reflect.TypeOf((*MockFilterService)(nil).TestNotify), ctx)
}

// Update mocks base method.
func (m *MockFilterService) Update(ctx context.Context, id int64, params service.FilterWriteParams) (model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, params)
	ret0, _ := ret[0].(model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFilterServiceMockRecorder) Update(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFilterService)(nil).Update), ctx, id, params)
}
