// Code generated by MockGen. DO NOT EDIT.
// Source: mcp_outbound_service.go
//
// Generated by this command:
//
//	mockgen -source=mcp_outbound_service.go -destination=mock/mcp_outbound_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	service "gist/backend/internal/service"
	mcp "gist/backend/internal/service/mcp"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMCPOutboundService is a mock of MCPOutboundService interface.
type MockMCPOutboundService struct {
	ctrl     *gomock.Controller
	recorder *MockMCPOutboundServiceMockRecorder
	isgomock struct{}
}

// MockMCPOutboundServiceMockRecorder is the mock recorder for MockMCPOutboundService.
type MockMCPOutboundServiceMockRecorder struct {
	mock *MockMCPOutboundService
}

// NewMockMCPOutboundService creates a new mock instance.
func NewMockMCPOutboundService(ctrl *gomock.Controller) *MockMCPOutboundService {
	mock := &MockMCPOutboundService{ctrl: ctrl}
	mock.recorder = &MockMCPOutboundServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPOutboundService) EXPECT() *MockMCPOutboundServiceMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockMCPOutboundService) Authorize(ctx context.Context, token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", ctx, token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Authorize indicates an expected call of Authorize.
func (mr *MockMCPOutboundServiceMockRecorder) Authorize(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockMCPOutboundService)(nil).Authorize), ctx, token)
}

// CallTool mocks base method.
func (m *MockMCPOutboundService) CallTool(ctx context.Context, name string, args map[string]any) (mcp.CallToolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallTool", ctx, name, args)
	ret0, _ := ret[0].(mcp.CallToolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallTool indicates an expected call of CallTool.
func (mr *MockMCPOutboundServiceMockRecorder) CallTool(ctx, name, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallTool", reflect.TypeOf((*MockMCPOutboundService)(nil).CallTool), ctx, name, args)
}

// Dispatch mocks base method.
func (m *MockMCPOutboundService) Dispatch(ctx context.Context, req service.MCPRPCRequest) (service.MCPRPCResponse, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", ctx, req)
	ret0, _ := ret[0].(service.MCPRPCResponse)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockMCPOutboundServiceMockRecorder) Dispatch(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockMCPOutboundService)(nil).Dispatch), ctx, req)
}

// GenerateToken mocks base method.
func (m *MockMCPOutboundService) GenerateToken(ctx context.Context) (service.MCPOutboundStatus, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", ctx)
	ret0, _ := ret[0].(service.MCPOutboundStatus)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockMCPOutboundServiceMockRecorder) GenerateToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockMCPOutboundService)(nil).GenerateToken), ctx)
}

// ReadResource mocks base method.
func (m *MockMCPOutboundService) ReadResource(ctx context.Context, uri string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadResource", ctx, uri)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadResource indicates an expected call of ReadResource.
func (mr *MockMCPOutboundServiceMockRecorder) ReadResource(ctx, uri any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadResource", reflect.TypeOf((*MockMCPOutboundService)(nil).ReadResource), ctx, uri)
}

// Resources mocks base method.
func (m *MockMCPOutboundService) Resources(ctx context.Context) ([]service.MCPResourceDescriptor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resources", ctx)
	ret0, _ := ret[0].([]service.MCPResourceDescriptor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resources indicates an expected call of Resources.
func (mr *MockMCPOutboundServiceMockRecorder) Resources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resources", reflect.TypeOf((*MockMCPOutboundService)(nil).Resources), ctx)
}

// RevokeToken mocks base method.
func (m *MockMCPOutboundService) RevokeToken(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeToken", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeToken indicates an expected call of RevokeToken.
func (mr *MockMCPOutboundServiceMockRecorder) RevokeToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeToken", reflect.TypeOf((*MockMCPOutboundService)(nil).RevokeToken), ctx)
}

// Status mocks base method.
func (m *MockMCPOutboundService) Status(ctx context.Context) (service.MCPOutboundStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(service.MCPOutboundStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockMCPOutboundServiceMockRecorder) Status(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockMCPOutboundService)(nil).Status), ctx)
}

// Tools mocks base method.
func (m *MockMCPOutboundService) Tools(ctx context.Context) []service.MCPToolDescriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tools", ctx)
	ret0, _ := ret[0].([]service.MCPToolDescriptor)
	return ret0
}

// Tools indicates an expected call of Tools.
func (mr *MockMCPOutboundServiceMockRecorder) Tools(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tools", reflect.TypeOf((*MockMCPOutboundService)(nil).Tools), ctx)
}

// UpdateOptions mocks base method.
func (m *MockMCPOutboundService) UpdateOptions(ctx context.Context, enabled, writeEnabled bool) (service.MCPOutboundStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOptions", ctx, enabled, writeEnabled)
	ret0, _ := ret[0].(service.MCPOutboundStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOptions indicates an expected call of UpdateOptions.
func (mr *MockMCPOutboundServiceMockRecorder) UpdateOptions(ctx, enabled, writeEnabled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOptions", reflect.TypeOf((*MockMCPOutboundService)(nil).UpdateOptions), ctx, enabled, writeEnabled)
}
