// Code generated by MockGen. DO NOT EDIT.
// Source: proxy_source_service.go
//
// Generated by this command:
//
//	mockgen -source=proxy_source_service.go -destination=mock/proxy_source_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "gist/backend/internal/model"
	service "gist/backend/internal/service"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProxySourceService is a mock of ProxySourceService interface.
type MockProxySourceService struct {
	ctrl     *gomock.Controller
	recorder *MockProxySourceServiceMockRecorder
	isgomock struct{}
}

// MockProxySourceServiceMockRecorder is the mock recorder for MockProxySourceService.
type MockProxySourceServiceMockRecorder struct {
	mock *MockProxySourceService
}

// NewMockProxySourceService creates a new mock instance.
func NewMockProxySourceService(ctrl *gomock.Controller) *MockProxySourceService {
	mock := &MockProxySourceService{ctrl: ctrl}
	mock.recorder = &MockProxySourceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxySourceService) EXPECT() *MockProxySourceServiceMockRecorder {
	return m.recorder
}

// Overview mocks base method.
func (m *MockProxySourceService) Overview(ctx context.Context) (*service.ProxySourceOverview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Overview", ctx)
	ret0, _ := ret[0].(*service.ProxySourceOverview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Overview indicates an expected call of Overview.
func (mr *MockProxySourceServiceMockRecorder) Overview(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Overview", reflect.TypeOf((*MockProxySourceService)(nil).Overview), ctx)
}

// ProxyURLForFeed mocks base method.
func (m *MockProxySourceService) ProxyURLForFeed(ctx context.Context, feedID int64) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProxyURLForFeed", ctx, feedID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// ProxyURLForFeed indicates an expected call of ProxyURLForFeed.
func (mr *MockProxySourceServiceMockRecorder) ProxyURLForFeed(ctx, feedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProxyURLForFeed", reflect.TypeOf((*MockProxySourceService)(nil).ProxyURLForFeed), ctx, feedID)
}

// ResolveForFeed mocks base method.
func (m *MockProxySourceService) ResolveForFeed(ctx context.Context, feed model.Feed) service.ProxyEffective {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveForFeed", ctx, feed)
	ret0, _ := ret[0].(service.ProxyEffective)
	return ret0
}

// ResolveForFeed indicates an expected call of ResolveForFeed.
func (mr *MockProxySourceServiceMockRecorder) ResolveForFeed(ctx, feed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveForFeed", reflect.TypeOf((*MockProxySourceService)(nil).ResolveForFeed), ctx, feed)
}

// ResolveForFeedID mocks base method.
func (m *MockProxySourceService) ResolveForFeedID(ctx context.Context, feedID int64) service.ProxyEffective {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveForFeedID", ctx, feedID)
	ret0, _ := ret[0].(service.ProxyEffective)
	return ret0
}

// ResolveForFeedID indicates an expected call of ResolveForFeedID.
func (mr *MockProxySourceServiceMockRecorder) ResolveForFeedID(ctx, feedID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveForFeedID", reflect.TypeOf((*MockProxySourceService)(nil).ResolveForFeedID), ctx, feedID)
}

// ResolveForFolder mocks base method.
func (m *MockProxySourceService) ResolveForFolder(ctx context.Context, folderID int64) service.ProxyEffective {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveForFolder", ctx, folderID)
	ret0, _ := ret[0].(service.ProxyEffective)
	return ret0
}

// ResolveForFolder indicates an expected call of ResolveForFolder.
func (mr *MockProxySourceServiceMockRecorder) ResolveForFolder(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveForFolder", reflect.TypeOf((*MockProxySourceService)(nil).ResolveForFolder), ctx, folderID)
}
