// Code generated by MockGen. DO NOT EDIT.
// Source: filter_repository.go
//
// Generated by this command:
//
//	mockgen -source=filter_repository.go -destination=mock/filter_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "krss/backend/internal/model"
	repository "krss/backend/internal/repository"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockFilterRepository is a mock of FilterRepository interface.
type MockFilterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFilterRepositoryMockRecorder
	isgomock struct{}
}

// MockFilterRepositoryMockRecorder is the mock recorder for MockFilterRepository.
type MockFilterRepositoryMockRecorder struct {
	mock *MockFilterRepository
}

// NewMockFilterRepository creates a new mock instance.
func NewMockFilterRepository(ctrl *gomock.Controller) *MockFilterRepository {
	mock := &MockFilterRepository{ctrl: ctrl}
	mock.recorder = &MockFilterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilterRepository) EXPECT() *MockFilterRepositoryMockRecorder {
	return m.recorder
}

// BumpMatchStats mocks base method.
func (m *MockFilterRepository) BumpMatchStats(ctx context.Context, stats map[int64]int64, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BumpMatchStats", ctx, stats, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// BumpMatchStats indicates an expected call of BumpMatchStats.
func (mr *MockFilterRepositoryMockRecorder) BumpMatchStats(ctx, stats, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BumpMatchStats", reflect.TypeOf((*MockFilterRepository)(nil).BumpMatchStats), ctx, stats, at)
}

// ClearLastError mocks base method.
func (m *MockFilterRepository) ClearLastError(ctx context.Context, filterID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearLastError", ctx, filterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearLastError indicates an expected call of ClearLastError.
func (mr *MockFilterRepositoryMockRecorder) ClearLastError(ctx, filterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearLastError", reflect.TypeOf((*MockFilterRepository)(nil).ClearLastError), ctx, filterID)
}

// Create mocks base method.
func (m *MockFilterRepository) Create(ctx context.Context, filter model.Filter) (model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, filter)
	ret0, _ := ret[0].(model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFilterRepositoryMockRecorder) Create(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFilterRepository)(nil).Create), ctx, filter)
}

// Delete mocks base method.
func (m *MockFilterRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFilterRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFilterRepository)(nil).Delete), ctx, id)
}

// GetAIJudgement mocks base method.
func (m *MockFilterRepository) GetAIJudgement(ctx context.Context, entryID int64, questionHash string) (bool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAIJudgement", ctx, entryID, questionHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAIJudgement indicates an expected call of GetAIJudgement.
func (mr *MockFilterRepositoryMockRecorder) GetAIJudgement(ctx, entryID, questionHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAIJudgement", reflect.TypeOf((*MockFilterRepository)(nil).GetAIJudgement), ctx, entryID, questionHash)
}

// GetByID mocks base method.
func (m *MockFilterRepository) GetByID(ctx context.Context, id int64) (model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFilterRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFilterRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockFilterRepository) List(ctx context.Context) ([]model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFilterRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFilterRepository)(nil).List), ctx)
}

// ListMatchedEntryIDs mocks base method.
func (m *MockFilterRepository) ListMatchedEntryIDs(ctx context.Context, filterID int64, limit int) ([]repository.MatchedEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatchedEntryIDs", ctx, filterID, limit)
	ret0, _ := ret[0].([]repository.MatchedEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatchedEntryIDs indicates an expected call of ListMatchedEntryIDs.
func (mr *MockFilterRepositoryMockRecorder) ListMatchedEntryIDs(ctx, filterID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatchedEntryIDs", reflect.TypeOf((*MockFilterRepository)(nil).ListMatchedEntryIDs), ctx, filterID, limit)
}

// ListMatches mocks base method.
func (m *MockFilterRepository) ListMatches(ctx context.Context, filterID int64, limit int) ([]model.FilterMatch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatches", ctx, filterID, limit)
	ret0, _ := ret[0].([]model.FilterMatch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatches indicates an expected call of ListMatches.
func (mr *MockFilterRepositoryMockRecorder) ListMatches(ctx, filterID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatches", reflect.TypeOf((*MockFilterRepository)(nil).ListMatches), ctx, filterID, limit)
}

// ListRevertImpact mocks base method.
func (m *MockFilterRepository) ListRevertImpact(ctx context.Context, filterID int64, limit int) ([]repository.RevertImpactEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRevertImpact", ctx, filterID, limit)
	ret0, _ := ret[0].([]repository.RevertImpactEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRevertImpact indicates an expected call of ListRevertImpact.
func (mr *MockFilterRepositoryMockRecorder) ListRevertImpact(ctx, filterID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRevertImpact", reflect.TypeOf((*MockFilterRepository)(nil).ListRevertImpact), ctx, filterID, limit)
}

// PruneMatches mocks base method.
func (m *MockFilterRepository) PruneMatches(ctx context.Context, keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneMatches", ctx, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// PruneMatches indicates an expected call of PruneMatches.
func (mr *MockFilterRepositoryMockRecorder) PruneMatches(ctx, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneMatches", reflect.TypeOf((*MockFilterRepository)(nil).PruneMatches), ctx, keep)
}

// RecordMatch mocks base method.
func (m *MockFilterRepository) RecordMatch(ctx context.Context, match model.FilterMatch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordMatch", ctx, match)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordMatch indicates an expected call of RecordMatch.
func (mr *MockFilterRepositoryMockRecorder) RecordMatch(ctx, match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordMatch", reflect.TypeOf((*MockFilterRepository)(nil).RecordMatch), ctx, match)
}

// SaveAIJudgement mocks base method.
func (m *MockFilterRepository) SaveAIJudgement(ctx context.Context, entryID int64, questionHash string, verdict bool, arg4 string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAIJudgement", ctx, entryID, questionHash, verdict, arg4, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAIJudgement indicates an expected call of SaveAIJudgement.
func (mr *MockFilterRepositoryMockRecorder) SaveAIJudgement(ctx, entryID, questionHash, verdict, arg4, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAIJudgement", reflect.TypeOf((*MockFilterRepository)(nil).SaveAIJudgement), ctx, entryID, questionHash, verdict, arg4, at)
}

// SetLastError mocks base method.
func (m *MockFilterRepository) SetLastError(ctx context.Context, filterID int64, message string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastError", ctx, filterID, message, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastError indicates an expected call of SetLastError.
func (mr *MockFilterRepositoryMockRecorder) SetLastError(ctx, filterID, message, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastError", reflect.TypeOf((*MockFilterRepository)(nil).SetLastError), ctx, filterID, message, at)
}

// Update mocks base method.
func (m *MockFilterRepository) Update(ctx context.Context, filter model.Filter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFilterRepositoryMockRecorder) Update(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFilterRepository)(nil).Update), ctx, filter)
}
