// Code generated by MockGen. DO NOT EDIT.
// Source: mcp_server_repository.go
//
// Generated by this command:
//
//	mockgen -source=mcp_server_repository.go -destination=mock/mcp_server_repository.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	model "krss/backend/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMCPServerRepository is a mock of MCPServerRepository interface.
type MockMCPServerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMCPServerRepositoryMockRecorder
	isgomock struct{}
}

// MockMCPServerRepositoryMockRecorder is the mock recorder for MockMCPServerRepository.
type MockMCPServerRepositoryMockRecorder struct {
	mock *MockMCPServerRepository
}

// NewMockMCPServerRepository creates a new mock instance.
func NewMockMCPServerRepository(ctrl *gomock.Controller) *MockMCPServerRepository {
	mock := &MockMCPServerRepository{ctrl: ctrl}
	mock.recorder = &MockMCPServerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPServerRepository) EXPECT() *MockMCPServerRepositoryMockRecorder {
	return m.recorder
}

// ClearOAuth mocks base method.
func (m *MockMCPServerRepository) ClearOAuth(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearOAuth", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearOAuth indicates an expected call of ClearOAuth.
func (mr *MockMCPServerRepositoryMockRecorder) ClearOAuth(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearOAuth", reflect.TypeOf((*MockMCPServerRepository)(nil).ClearOAuth), ctx, id)
}

// CountFeedsUsing mocks base method.
func (m *MockMCPServerRepository) CountFeedsUsing(ctx context.Context, id int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFeedsUsing", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFeedsUsing indicates an expected call of CountFeedsUsing.
func (mr *MockMCPServerRepositoryMockRecorder) CountFeedsUsing(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFeedsUsing", reflect.TypeOf((*MockMCPServerRepository)(nil).CountFeedsUsing), ctx, id)
}

// Create mocks base method.
func (m *MockMCPServerRepository) Create(ctx context.Context, server model.MCPServer) (model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, server)
	ret0, _ := ret[0].(model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMCPServerRepositoryMockRecorder) Create(ctx, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMCPServerRepository)(nil).Create), ctx, server)
}

// Delete mocks base method.
func (m *MockMCPServerRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMCPServerRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMCPServerRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMCPServerRepository) GetByID(ctx context.Context, id int64) (model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMCPServerRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMCPServerRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockMCPServerRepository) List(ctx context.Context) ([]model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMCPServerRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMCPServerRepository)(nil).List), ctx)
}

// SetLastFailure mocks base method.
func (m *MockMCPServerRepository) SetLastFailure(ctx context.Context, id int64, failureJSON *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastFailure", ctx, id, failureJSON)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastFailure indicates an expected call of SetLastFailure.
func (mr *MockMCPServerRepositoryMockRecorder) SetLastFailure(ctx, id, failureJSON any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastFailure", reflect.TypeOf((*MockMCPServerRepository)(nil).SetLastFailure), ctx, id, failureJSON)
}

// SetLastTransport mocks base method.
func (m *MockMCPServerRepository) SetLastTransport(ctx context.Context, id int64, transport string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastTransport", ctx, id, transport)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastTransport indicates an expected call of SetLastTransport.
func (mr *MockMCPServerRepositoryMockRecorder) SetLastTransport(ctx, id, transport any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastTransport", reflect.TypeOf((*MockMCPServerRepository)(nil).SetLastTransport), ctx, id, transport)
}

// TouchLastUsed mocks base method.
func (m *MockMCPServerRepository) TouchLastUsed(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockMCPServerRepositoryMockRecorder) TouchLastUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockMCPServerRepository)(nil).TouchLastUsed), ctx, id)
}

// Update mocks base method.
func (m *MockMCPServerRepository) Update(ctx context.Context, server model.MCPServer) (model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, server)
	ret0, _ := ret[0].(model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMCPServerRepositoryMockRecorder) Update(ctx, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMCPServerRepository)(nil).Update), ctx, server)
}

// UpdateOAuthTokens mocks base method.
func (m *MockMCPServerRepository) UpdateOAuthTokens(ctx context.Context, id int64, server model.MCPServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOAuthTokens", ctx, id, server)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOAuthTokens indicates an expected call of UpdateOAuthTokens.
func (mr *MockMCPServerRepositoryMockRecorder) UpdateOAuthTokens(ctx, id, server any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOAuthTokens", reflect.TypeOf((*MockMCPServerRepository)(nil).UpdateOAuthTokens), ctx, id, server)
}

// UpdateStatus mocks base method.
func (m *MockMCPServerRepository) UpdateStatus(ctx context.Context, id int64, connected bool, lastError *string, toolCount, resourceCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, connected, lastError, toolCount, resourceCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockMCPServerRepositoryMockRecorder) UpdateStatus(ctx, id, connected, lastError, toolCount, resourceCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockMCPServerRepository)(nil).UpdateStatus), ctx, id, connected, lastError, toolCount, resourceCount)
}
